name: rehome_cli
channels:
  - defaults
dependencies:
  - python=3.10.4
  - pip:
    - numpy==1.21.5
    - pandas==1.4.2
    - pip==21.2.4
    - pyyaml==6.0
    - ruamel-yaml==0.17.21
    - ruamel-yaml-clib==0.2.6
    - requests==2.27.1

